name: publish package

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  publish_npm_for_cli:
    runs-on: ubuntu-latest

    steps:
      - run: echo '${{ toJSON(github) }}'



