name: publish package

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  publish_npm_for_cli:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(cli)')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: cd package/cli && npm i

      - run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}



