name: publish package

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  # cli
  publish_cli:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(cli)') && contains(github.event.commits[0].message, '[pub]')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: cd package/cli && npm i

      - run: git config --local user.email "bot@auto.xunserver.cn" && git config --local user.name "bot"

      - run: cd package/cli && npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
  # vui
  publish_vui:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(vui)') && contains(github.event.commits[0].message, '[pub]')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: cd package/vui && npm i

      - run: git config --local user.email "bot@auto.xunserver.cn" && git config --local user.name "bot"

      - run: cd package/vui && npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  # style
  publish_style:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(style)') && contains(github.event.commits[0].message, '[pub]')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - run: cd package/style && npm i

      - run: git config --local user.email "bot@auto.xunserver.cn" && git config --local user.name "bot"

      - run: cd package/style && npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  # doc
  deploy_doc:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(doc)')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm i -g pnpm

      - run: pnpm install

      - run: git config --local user.email "bot@auto.xunserver.cn" && git config --local user.name "bot"

      - run: pnpm -F @xunserver/style run build

      - run: pnpm -F @xunserver/vui run build

      - run: pnpm -F @xunserver/doc run build

      - name: deploy github
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 和gitee的使用一个
          external_repository: xuncool/doc
          publish_branch: main
          publish_dir: ./package/doc/dist
          cname: ${{ secrets.CNAME }}

  deploy_gitee_doc:
    runs-on: ubuntu-latest
    if: contains(github.event.commits[0].message, '(doc)')
    steps:
      - name: pull code
        uses: actions/checkout@master

      - name: node and npm
        uses: actions/setup-node@master
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm i -g pnpm

      - run: pnpm install

      - run: git config --local user.email "bot@auto.xunserver.cn" && git config --local user.name "bot"

      - run: pnpm -F @xunserver/style run build

      - run: pnpm -F @xunserver/vui run build

      - run: pnpm -F @xunserver/doc run build:doc

      - name: deploy github
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 和gitee的使用一个
          external_repository: xuncool/doc
          publish_branch: doc
          publish_dir: ./package/doc/dist
          cname: ${{ secrets.CNAME }}

  deploy-gitee:
    needs: deploy_gitee_doc
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@master
        with:
          repository: "xuncool/doc"

      - name: sync shell cmd
        run: |
          GITEE_GIT_ADDR="git@gitee.com:xuncool/doc.git"
          SSHPATH="$HOME/.ssh"
          git fetch --unshallow
          rm -rf "$SSHPATH"
          mkdir -p "$SSHPATH"
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > "$SSHPATH/id_rsa"
          chmod 600 "$SSHPATH/id_rsa"
          sudo sh -c "echo StrictHostKeyChecking no >>/etc/ssh/ssh_config"
          git checkout doc
          git remote add upstream $GITEE_GIT_ADDR
          git push upstream doc main --force

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: "xuncool/doc"
          branch: main
